### ISSUE TITLE
inject not working with nuxt-property-decorator on ssr  from b55dc9d8

### ISSUE THREAD

**Issue by aldarund** [nuxt/bridge#408]
### Environment

![image](https://user-images.githubusercontent.com/571159/178735620-147a6e1d-f412-4319-91ef-cb925bb41956.png)

### Reproduction

https://codesandbox.io/s/nuxt-nuxt-js-typescript-forked-7pmgqn?file=/nuxt.config.ts here non working examples with latest bridge
here working example with last working bridge https://codesandbox.io/s/nuxt-nuxt-js-typescript-forked-lkqd1w?file=/package.json
caused by https://github.com/nuxt/bridge/commit/b55dc9d8443930b53007393e0d1c413d8f873028
maybe something to do with transpiling\paths, if use just use vue-class-component instead of nuxt-property-decorator - it works.
https://codesandbox.io/s/nuxt-nuxt-js-typescript-forked-7pmgqn?file=/pages/index2.vue
But all nuxt-property-decorator do is just reexport 
export { default as Component, mixins } from 'vue-class-component';

### Describe the bug

inject not working properly on ssr

**Comment by chesterlaykin** [comment]
Does **nuxt-property-decorator** not work with **nuxt/bridge** right now?
I got different errors like:
 `"TypeError: Cannot read properties of undefined (reading 'state')"`
`_ssrEscape is not a function) inject not working with nuxt-property-decorator on ssr from b55dc9d`
`Property or method "_ssrEscape" is not defined onthe instance but referenced during render.`
`Property or method "_ssrNode" is not defined on the instance but referenced during render.`

So I tried to use the last working version: **3.0.0-27611430.cf4761a**
But that version had a problem when running**build** , then **start**, it doesn't work (Reached heap limit Allocation failed ). But that seems to be fixed when I try the current latest version **3.0.0-27711990.d463650**

**Comment by danielroe** [comment]
You probably need to transpile `nuxt-property-decorator` and `vue-class-component`, now that Vue 2.7 has built-in composition API support.

https://codesandbox.io/s/nuxt-nuxt-js-typescript-forked-94w6ey?file=/nuxt.config.ts:163-211
